### ISSUE TITLE
The README.md reflects 1.11 which does not have ExportBinder

### ISSUE THREAD

**Issue by ajeeshpu** [martint/jmxutils#30]
```xml
<dependency>
    <groupId>org.weakref</groupId>
    <artifactId>jmxutils</artifactId>
    <version>1.11</version>
</dependency>
```

The maven dependency does not reflect the correct class since ExportBinder is unavailable in 1.11. Have checked version 1.18 where it is available. May be you could point to the latest considering the other code samples are up to date

**Comment by martint** [comment]
Fixed, thanks!
